In [2]:
import numpy as np

$
\begin{bmatrix} 
a & b 
\end{bmatrix}
\quad
\begin{matrix} 
a & b \\
c & d 
\end{matrix}
\quad
\begin{pmatrix} 
a & b \\
c & d 
\end{pmatrix}
\quad
\begin{bmatrix} 
a & b \\
c & d 
\end{bmatrix}
\quad
\begin{vmatrix} 
a & b \\
c & d 
\end{vmatrix}
\quad
\begin{Vmatrix} 
a & b \\
c & d 
\end{Vmatrix}
$


In [40]:
MyExampleArray1D = np.array([1, 
                      12,  
                      50,  
                      1,  
                      6])
print(MyArray1D)

[ 1 12 50  1  6]


In [39]:
MyArray2D = np.array([[1, 12,  50,  1,  6],      
                      [1, 12,  50,  1,  6]])
print(MyArray2D)



[[ 1 12 50  1  6]
 [ 1 12 50  1  6]]


In [33]:
MyArray2D = np.array([MyArray1D,MyArray1D])
print(MyArray2D)

[[ 1 12 50  1  6]
 [ 1 12 50  1  6]]


In [37]:
MyArray3D = np.array([[[1, 12,  50,  1,  6],
                      [1, 12,  50,  1,  6]],
                      
                    [[1, 12,  50,  1,  6],
                      [1, 12,  50,  1,  6]],
                      
                    [[1, 12,  50,  1,  6],
                      [1, 12,  50,  1,  6]]])
print(MyArray3D)




[[[ 1 12 50  1  6]
  [ 1 12 50  1  6]]

 [[ 1 12 50  1  6]
  [ 1 12 50  1  6]]

 [[ 1 12 50  1  6]
  [ 1 12 50  1  6]]]


In [3]:
list = [1, 2, 3, 4, 5]
array = np.array([list])
print(array)

[[1 2 3 4 5]]


In [5]:
array2 = np.array([4,5,6])

In [6]:
print(array2)


[4 5 6]


In [24]:
array3 = np.array([[4,5,6],[3,2,1]])
print(array3)

[[4 5 6]
 [3 2 1]]


In [28]:
List1 = [1,  12,  50,  1,  6]
print(List1)
MyExampleArray = np.array(List1)
print(MyExampleArray)
MyExampleArray.ndim




[1, 12, 50, 1, 6]
[ 1 12 50  1  6]


1

In [27]:
List1 = [1,  12,  50,  1,  6]
MyExampleArray = np.array([List1,List1,List1])
print(MyExampleArray)
MyExampleArray.ndim

[[ 1 12 50  1  6]
 [ 1 12 50  1  6]
 [ 1 12 50  1  6]]


2

In [14]:
MyExampleArray.size

5

In [16]:
MyExampleArray.ndim

1