## Linear Algebra

NumPy allows for many useful packages, and as scientists and engineers one of the most useful is the ```linalg``` package.

This package provides us with many prewritten functions to perform linear algebra operations.

In [2]:
import numpy as np

First let's define a matrix just so we can examine some of the functions with which ```linalg``` provides us.

In [3]:
matrix = np.random.randn(4, 4)

In [4]:
print(matrix)

[[-0.99827394 -2.45543823  0.27000413  1.29266128]
 [ 0.3076352   0.22443279  0.36836813 -0.64910047]
 [-0.63581046 -1.4875931   0.11868613 -1.25812536]
 [-0.67279943  0.31493412 -0.12112133  0.06091167]]


We can calculate the inverse of a matrix by calling the ```inv()``` function from the ```linalg``` package

In [5]:
inv = np.linalg.inv(matrix)

To prove that it is in fact the inverse of the matrix we can multiply ```inv``` and ```matrix``` whose result should be the identity matrix.

In [6]:
experimental_identity = np.matmul(matrix, inv)
print(experimental_identity)

[[ 1.00000000e+00  3.27609479e-18  7.28242291e-18 -2.06672375e-16]
 [ 1.69857103e-17  1.00000000e+00 -2.12108401e-17  9.79809298e-17]
 [-5.72710501e-17 -7.58347159e-18  1.00000000e+00 -1.48901119e-16]
 [-3.77358871e-17 -1.81555187e-17  9.38020759e-18  1.00000000e+00]]


We can see that this is close to the identity matrix to the degree of some rounding errors off of the main diagonal. But what if we wanted NumPy to check for us? Then we can use the ```allclose()``` function to check if all the values in one matrix are close to some degree to another matrix. 

First we have to have an identity matrix to which we can compare ```experimental_identity```. For this we can use the ```eye()``` function. This function creates a 2-dimensional array with 1's on the diagonal and 0's everywhere else.

In [7]:
true_identity = np.eye(4)
print(true_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Now we can compare ```experimental_identity``` and ```true_identity```.

In [8]:
print(np.allclose(experimental_identity, true_identity))

True


The ```numpy``` and ```linalg``` packages also allows some basic but usually tedious linear algebra operations should we have to code them ourselves. These operations include but are not limited to:

```sum()```: calculates the elementwise sum of a matrix

```trace()```: calculates the trace of a matrix

```det()```: calculates the determinant of a matrix

Let's define a random matrix of integers and check these functions.

In [9]:
matrix = np.random.randint(10, size=(4,4))
matrix_sum = np.sum(matrix)
matrix_trace = np.trace(matrix)
matrix_det = np.linalg.det(matrix)

In [10]:
print(matrix)
print(matrix_sum)
print(matrix_trace)
print(matrix_det)

[[2 3 9 0]
 [5 6 8 7]
 [6 2 5 6]
 [8 2 4 9]]
82
22
-12.999999999999954


Arguably one of the most important functions that comes in the ```linalg``` package is ```norm()```

This function calculates the norm of a matrix or vector and can be used in many different cases. Let's see how it works on two 2-D vectors.

In [12]:
a = np.array([5, 5])
b = np.array([1, 2])
print(np.linalg.norm(a))
print(np.linalg.norm(b))

7.0710678118654755
2.23606797749979


Now why might this be extremely useful for data scientists? Well it allows us to quickly calculate the distance between two data points, as data points are represented as vectors. 

Let's look at the image below for why this is so:

![title](Distance_Between_Vectors.PNG)

So the distance between these two vectors can be calculated with the following line of code!

In [16]:
print(np.linalg.norm(a-b))

5.0


This above line of code is one of the fundamental principals of machine learning and optimization tasks. When we are training a machine to perform a task well we are asking it to predict an answer. Then we compare its prediction to some data to which we know the correct answer (what we call training data). Then, depending on how close its prediction is, the machine updates itself and tries again until it converges closer to the answer. Thus, the goal of machine learning is minimizing the distance between the prediction of the machine and the true answer.