# Unit 3 Lecture 1 -  Basic NumPy

ESI4628: Decision Support Systems for Industrial Engineers<br>
University of Central Florida
Dr. Ivan Garibay, Ramya Akula, Mostafa Saeidi, Madeline Schiappa, and Brett Belcher. 
https://github.com/igaribay/DSSwithPython/blob/master/DSS-Week03/Notebook/DSS-Unit03-Lecture01.2018.ipynb

## Notebook Learning Objectives
After studying this notebook students should be able to:
- Use the NumPy Python package to execute basic mathematical operations
- Use Numpy to create and manipulate arrays

# Overview

Numpy is the fundamental package for scientific computing in Python:
- Extremely useful for doing anything from simple to complex mathematics operations
- NumPy gives a useful application programming interface (API) for data manipulation through its matrix operations
- It is conventional to import NumPy as "np"

For more information about Numpy:
http://www.numpy.org/


### The following line "loads" numpy into this Notebook

In [25]:
import numpy as np

### Create an array
- Arrays are list of numbers

In [178]:
MyList = [1,12,50,1,6]
MyExampleArray = np.array(MyList)
print(MyExampleArray)

[ 1 12 50  1  6]


In [128]:
print(MyExampleArray.size)
print(MyExampleArray.ndim)
print(MyExampleArray.shape)
print(MyExampleArray.dtype)

5
1
(5,)
int64


In [184]:
MyExampleArray = np.array([1,12,50,1,6])
copy1 = MyExampleArray[1:4].copy()
print(copy1)

[12 50  1]


### One dimensional array
- We can also create an array by just enumerating its elements directly
- One dimensional arrays are a list of numbers
- Lets create the following one dimensional array:<br>
\begin{equation*}
\begin{bmatrix} 
1 & 12 & 50 & 0 & 6 
\end{bmatrix}
\end{equation*}

In [129]:
MyArray1D = np.array([
                        1,
                        12,
                        50,
                        1,
                        6
                    ])
print(MyArray1D)

[ 1 12 50  1  6]


### Two dimensional array
A two dimensional array is simply a list containing "list of numbers" as elements. For example see the following two dimensional array:
\begin{equation*}
\begin{bmatrix} 
\begin{bmatrix}1 & 12 & 50 & 0 & 6\end{bmatrix} \\
\begin{bmatrix}8 & 4 & 16 & 6 & 69\end{bmatrix} \\
\begin{bmatrix}56 & 6 & 87 & 0 & 39\end{bmatrix} \\
\begin{bmatrix}89 & 4 & 50 & 2 & 5\end{bmatrix} 
\end{bmatrix}
\end{equation*}
<br>
alternatively, omiting the interior brackets, simply:<br>
\begin{equation*}
\begin{bmatrix} 
1 & 12 & 50 & 0 & 6 \\
8 & 4 & 16 & 6 & 69\\
56 & 6 & 87 & 0 & 39\\
89 & 4 & 50 & 2 & 5
\end{bmatrix}
\end{equation*}
<br>
Below, lets create this array as <code>MyArray2D</code>

In [132]:
MyArray2D = np.array([
                        [1, 12,  50,  1,  6],
                        [8 , 4 , 16 , 6 , 69],
                        [56 , 6 , 87 , 0 , 39],
                        [89 , 4 , 50 , 2 , 5]
                     ])
print(MyArray2D)


[[ 1 12 50  1  6]
 [ 8  4 16  6 69]
 [56  6 87  0 39]
 [89  4 50  2  5]]


In [131]:
MyArray2D[0,0]

1

In [135]:
MyArray2D[2,0]

56

In [136]:
MyArray2D[3,4]

5



### Three dimensional arrays
A three dimensional array is simply a list containing "list of list of numbers" as elements. For example see the following three dimensional array:

\begin{equation*}
\begin{bmatrix} 
\begin{bmatrix} 
1 & 12 & 50 & 0 & 6 \\
8 & 4 & 16 & 6 & 69\\
56 & 6 & 87 & 0 & 39\\
89 & 4 & 50 & 2 & 5
\end{bmatrix}
& 
\begin{bmatrix} 
1 & 55 & 50 & 0 & 4 \\
5 & 43 & 6 & 16 & 2\\
5 & 62 & 8 & 1 & 5\\
9 & 54 & 0 & 12 & 4
\end{bmatrix}
& 
\begin{bmatrix} 
5 & 13 & 9 & 89 & 5 \\
66 & 4 & 4 & 4 & 3\\
5 & 6 & 4 & 4 & 5\\
29 & 4 & 4 & 4 & 8
\end{bmatrix}
& 
\begin{bmatrix} 
1 & 9 & 26 & 12 & 5 \\
4 & 5 & 55 & 5 & 4\\
5 & 0 & 0 & 0 & 6\\
81 & 1 & 1 & 1 & 44
\end{bmatrix}
\end{bmatrix}
\end{equation*}
<br>
Below, lets create this array as <code>MyArray3D</code>

In [33]:
MyArray3D = np.array([
                        [
                            [1, 12,  50,  1,  6],
                            [8 , 4 , 16 , 6 , 69],
                            [56 , 6 , 87 , 0 , 39],
                            [89 , 4 , 50 , 2 , 5]
                        ],
                        [
                            [1 , 55 , 50 , 0 , 4],
                            [5 , 43 , 6 , 16 , 2],
                            [5 , 62 , 8 , 1 , 5],
                            [9 , 54 , 0 , 12 , 4]
                        ],
                        [
                            [5 , 13 , 9 , 89 , 5],
                            [66 , 4 , 4 , 4 , 3],
                            [5 , 6 , 4 , 4 , 5],
                            [29 , 4 , 4 , 4 , 8]
                        ],
                        [
                            [1 , 9 , 26 , 12 , 5],
                            [4 , 5 , 55 , 5 , 4],
                            [5 , 0 , 0 , 0 , 6],
                            [81 , 1 , 1 , 1 , 44]
                        ]
                     ])
print(MyArray3D)

[[[ 1 12 50  1  6]
  [ 8  4 16  6 69]
  [56  6 87  0 39]
  [89  4 50  2  5]]

 [[ 1 55 50  0  4]
  [ 5 43  6 16  2]
  [ 5 62  8  1  5]
  [ 9 54  0 12  4]]

 [[ 5 13  9 89  5]
  [66  4  4  4  3]
  [ 5  6  4  4  5]
  [29  4  4  4  8]]

 [[ 1  9 26 12  5]
  [ 4  5 55  5  4]
  [ 5  0  0  0  6]
  [81  1  1  1 44]]]


In [62]:
print(MyArray3D.size)
print(MyArray3D.ndim)
print(MyArray3D.shape)
print(MyArray3D.dtype)

80
3
(4, 4, 5)
int64


# Intro to arrays, attributes, and functions

First let us create a normal list and convert it to a NumPy array

In [85]:
list = [1, 2, 3, 4, 5]
array = np.array([list])
print(array)

[[1 2 3 4 5]]


Now the ```array``` variable has all the functionality of NumPy! Let's make a second list so we can start seeing some of NumPy's built in operations

In [86]:
list2 = [6, 7, 8, 9, 10]
array2 = np.array([list2])
print(array2)

[[ 6  7  8  9 10]]


Now with two arrays, we can use them to perform mathematical operations:
\begin{equation*}
\begin{bmatrix} 
1 & 2 & 3 & 4 & 5 
\end{bmatrix}
+
\begin{bmatrix} 
6 & 7 & 8 & 9 & 10 
\end{bmatrix}
\end{equation*}
\begin{equation*}
\begin{bmatrix} 
1 & 2 & 3 & 4 & 5 
\end{bmatrix}
-
\begin{bmatrix} 
6 & 7 & 8 & 9 & 10 
\end{bmatrix}
\end{equation*}
\begin{equation*}
\begin{bmatrix} 
1 & 2 & 3 & 4 & 5 
\end{bmatrix}
\times
\begin{bmatrix} 
6 & 7 & 8 & 9 & 10 
\end{bmatrix}
\end{equation*}
\begin{equation*}
\begin{bmatrix} 
1 & 2 & 3 & 4 & 5 
\end{bmatrix}
\div
\begin{bmatrix} 
6 & 7 & 8 & 9 & 10 
\end{bmatrix}
\end{equation*}

In [104]:
add = np.add(array, array2) # Performs elementwise adding
sub = np.subtract(array, array2) # Performs elementwise subtraction
mult = np.matmul(array, array2) # Performs matrix multiplication
div = np.divide(array, array2) # Performs elementwise division

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

Can anyone spot the problem in the code above?

NumPy arrays have great attributes such as ```ndim```, ```shape```, ```size```, and ```dtype```.

```ndim```: The number of dimensions

```shape```: The size of each dimension presented as a tuple

```size```: The total size of the array

```dtype```: The data type of the array

Using these attributes, we can find the problem.

In [105]:
print("array has", array.ndim, "dimensions")
print("array has the shape", array.shape)
print("array is of size", array.size)
print("array is of type", array.dtype)
print()
print("array2 has", array2.ndim, "dimensions")
print("array2 has the shape", array2.shape)
print("array2 is of size", array2.size)
print("array2 is of type", array2.dtype)

('array has', 2, 'dimensions')
('array has the shape', (1, 5))
('array is of size', 5)
('array is of type', dtype('int64'))
()
('array2 has', 2, 'dimensions')
('array2 has the shape', (1, 5))
('array2 is of size', 5)
('array2 is of type', dtype('int64'))


The problem is because ```array``` and ```array2``` are both of shape ```1 x 5``` meaning they cannot be multiplied together. A matrix of shape ```1 x 5``` can only be multiplied by a matrix of shape ```5 x k``` which would produce a matrix of shape ```1 x k```

Let's perform a simple transformation to allow the matrix multiplication to work! First let's comment out the bugged line earlier.

In [106]:
array2_transformed = array2.transpose()

We can check this new array's ```shape```

In [107]:
print(array2_transformed.shape)

(5, 1)


Now we can perform our matrix multiplication! Since the multiplication is ```(1 x 5) x (5 x 1)```, this should result in an array of size ```1 x 1```

In [108]:
mult = np.matmul(array, array2_transformed)
print(mult.shape)

(1, 1)


In [109]:
print(add)
print(sub)
print(mult)
print(div)

[[ 7  9 11 13 15]]
[[-5 -5 -5 -5 -5]]
[[130]]
[[0 0 0 0 0]]


# Manipulating Arrays

Now that we have a basic overview of NumPy arrays, we can work to manipulate them

First let me introduce a new function for instantiating arrays similar to the arrays we had before called ```arange()```

In [94]:
x1 = np.arange(12)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Indexing Arrays

We can index arrays similar to in other programming language. 

__Note__: Remember that array indexing starts at index 0

In [95]:
print(x1[0])
print(x1[4])
print(x1[11])

0
4
11


Python also allows for indexing backwards by using negative indicies. So we can access the last element of an array with index ```-1```

In [96]:
print(x1[-1])

11


## Slicing Arrays: Subarrays

Accessing subarrays can be done witht he slice notation which is marked by the ```:``` character. The format is as follows:

``` x[start:stop:step] ```

where the default values are ```start = 0```, ```stop = size of dimension```, and ```step = 1```

So we can access the first five elements by overwriting the default of ```stop```

In [97]:
print(x1[:5])

[0 1 2 3 4]


We can access the middle elements by overwriting the default of ```start``` and ```stop```

In [14]:
print(x1[4:7])

[4 5 6]


We can access every other element by overwriting the default of ```step```

In [98]:
print(x1[::2])

[ 0  2  4  6  8 10]


__Note__: Having a negative ```step``` value is valid; however, the default of ```start``` and ```stop``` are swapped

Thus we can reverse an array in the following manner

In [99]:
print(x1[::-1])

[11 10  9  8  7  6  5  4  3  2  1  0]


## Array Dimensions

It is important to note the ```shape``` of the above array

In [100]:
print(x1.shape)

(12,)


This is different than the shape we have previously seen. This is a 1-dimensional array of with 12 elements.

Sometimes this is what we want, but what if we rather wanted a matrix with 1 row and 12 columns?

We can use the ```reshape()``` function in this case to reshape the dimensions of the array

In [101]:
x1 = x1.reshape((1, 12))
print(x1.shape)
print(x1)

(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


We can also use the ```random``` package to instantiate randomly generated arrays to work with

In [164]:
np.random.seed(0) # The seed allows for consistent examples

x1 = np.random.randint(10, size=(1, 12))
print(x1)

[[5 0 3 3 7 9 3 5 2 4 7 6]]


We can use the ```reshape()``` function to change ```x1``` to be of a different shape like ```3 x 4```

In [165]:
x1 = x1.reshape((3, 4))
print(x1)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


## Indexing and Splicing with Multi-Dimensional Arrays

It can be seen how we can extend the earlier techniques of indexing and splicing to multiple dimensions.

For indexing, it is as simple as specifying the index in all of the dimensions you wish to index

In [21]:
print(x1[1][3])

5


If we can use this same idea to not only access specific elements, but even rows or columns of our array

In [22]:
print(x1[1])
# An equivalent line of code using the splicing notation is
# print(x1[1][:])

[7 9 3 5]


We can use splicing notation along with the indexing notation to do things like get subarrays from multi-dimensional arrays

In [23]:
print(x1[1][2:4])

[3 5]


## Subarrays are views and not copies

It is best to know early on that when you slice arrays you are not getting back a copy of that subarray, but simply a view of that subarray.

Thus, any changes made to the view affect the original array as you will see below. First let's print our array

In [24]:
print(x1)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


Now let's print a subarray of ```x1``` that we will define as ```x1_subarray```

In [25]:
x1_subarray = x1[2][1:]
print(x1_subarray)

[4 7 6]


Now let's make a change to ```x1_subarray``` and see how it affects ```x1```

In [26]:
x1_subarray[0] = -1
print(x1_subarray)
print(x1)

[-1  7  6]
[[ 5  0  3  3]
 [ 7  9  3  5]
 [ 2 -1  7  6]]


While this may seem unuseful it actually is a great feature when working with big data. If we have a large quantity of data, then we can use this to access and process smaller chuncks of our large dataset.

For now though, it would be best to know how to make actual copies of an array. We can do this using the ```copy()``` function

In [27]:
x1_subarray_copy = x1[2][1:].copy()
print(x1_subarray_copy)

[-1  7  6]


In [28]:
x1_subarray_copy[0] = 100
print(x1_subarray_copy)

[100   7   6]


Now let's see how making this change to the copy of the subarray didn't change the original ```x1``` at all.

In [29]:
print(x1)

[[ 5  0  3  3]
 [ 7  9  3  5]
 [ 2 -1  7  6]]


# Exercises

__3.1__ Add the following arrays:
\begin{equation*}
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix} 
+
\begin{bmatrix} 
1 & 1 \\
1 & 1
\end{bmatrix} 
\end{equation*}

__3.1 Solution:__

In [1]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
np.add(A,B)

NameError: name 'np' is not defined

__3.2__ Multiply the following arrays:
$
\begin{bmatrix} 
1 & 2 \\
\end{bmatrix} 
\times
\begin{bmatrix} 
1  \\
1 
\end{bmatrix} 
$


__3.2 Solution:__

In [124]:
A = np.array([[1,2]])
B = np.array([[1],[1]])
np.matmul(A,B)

array([[3]])

__3.3__ Multiply the following arrays:
$
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix} 
\times
\begin{bmatrix} 
1 & 1 \\
1 & 1
\end{bmatrix} 
$

__3.3 Solution:__

In [187]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
np.matmul(A,B)

array([[3, 3],
       [7, 7]])

__3.5__ Create a length-100 integer array filled with zeros. _Hint: use function <code>np.zeros()</code>_

__3.6__  Create a 5x6 floating point array filled with ones. _Hint: use function <code>np.ones()</code>_

__3.7__  Create a 8x8 array filled with 3.14159. _Hint: use function <code>np.full()</code>_

__3.8__  Create an array filled with a sequence starting at 20 ending at 80 and incrementing by 4. _Hint: use function <code>np.arange()</code>_

__3.9__  Create a 50x50 array of uniformly distributed random number between 0 and 1. _Hint: use function <code>np.random.random()</code>_

__3.10__  Create a 10x10 identity matrix (full of zeros except on the diagonal going from the left-top to the right-bottom) _Hint: use function <code>np.eye()</code>_

__3.10 Solution:__

In [190]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Applications

# Homework (not graded)
Please complete all the exercises on this Notebook. Some exercises will be solved in class, but you should complete solving all the remaining exersices at the end of each Notebook on every class. If you can not solve an exercise, please contact the class teaching assistant for help inmmediately.

# References
- Numpy, http://www.numpy.org/
- Matrix multiplication, https://en.wikipedia.org/wiki/Matrix_multiplication

_Last updated on 9.4.18 2:09am<br>
(C) 2018 Complex Adaptive Systems Laboratory all rights reserved._